### ISSUE TITLE
Automation of corpus ingestion and model generation

### ISSUE THREAD

**Issue by meiertgrootes** [ADAH-EviDENce/evidence#1]
In many cases, a user will be content with the default corpus ingestion and model training settings
For such a user, it would be desirable if these steps were performed automatically (rather than requiring the user to run the notebooks), with the results subsequently being loaded into the GUI for access.

additional points
- for more advanced users access to the notebooks would still be desirable
- model training can take a while (hours) so this could be an automated step that would require the user to come back the next day

**Comment by jspaaks** [comment]
Can this be closed? Users have access to the model generation container, and they see a progressbar during the automated training part.
