### ISSUE TITLE
Update RSD entry

### ISSUE THREAD

**Issue by meiertgrootes** [ADAH-EviDENce/evidence#116]
- [x] Update text in RSD entry
- [x] fix reference in journal mentions
- [ ] link other material from deliverables (when it becomes available)

**Comment by jspaaks** [comment]
also added https://www.ou.nl/-/workshop-gebruikerservaring-evidence-over-het-digitale-geesteswetenschappen?inheritRedirect=true&redirect=%2Fweb%2Fopen-universiteit%2Fzoekresultaten%3Fq%3Devidence

and the blog https://blog.esciencecenter.nl/digital-technologies-to-analyze-eyewitness-accounts-of-mass-violence-dddfc6fd3866

**Comment by meiertgrootes** [comment]
@jspaaks I updated the RSD entry. Please let me know if it check-out when you find the time.

**Comment by jspaaks** [comment]
Looks good, closing the issue.
