### ISSUE TITLE
Make your suggestions for a name here

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#13]
**myopic**

close reading, get it?

**Comment by fdiblen** [comment]
I have Myopia. I feel offended.

**Comment by jspaaks** [comment]
That's because of all the close reading you've been doing @fdiblen

**Comment by cwmeijer** [comment]
adiutor (assistent/helper in latin, for instance in a library)
maybe catchy for the target audience.

**Comment by cwmeijer** [comment]
I now get the joke myopic. I had to look it up ;-)
MyTopic could be an alternative to have the same joke less obviously

**Comment by cwmeijer** [comment]
We thought about:
myopic 0.5
myopia
mytopic
adiutor
evidence 3.0
close-reader 0.5

We voted for:
evidence

**Comment by cwmeijer** [comment]
Subtitle:
Assisted close reading

**Comment by jspaaks** [comment]
change repo name, closing
