### ISSUE TITLE
Simplify interface EviDENCe framework evidence Gui

### ISSUE THREAD

**Issue by meiertgrootes** [ADAH-EviDENce/evidence#2]
Currently, the docker framework provided in the [EviDENce_doc2vec_docker_framework](https://github.com/ADAH-EviDENce/EviDENce_doc2vec_docker_framework) repository provides a jupyterlab environment the user can use to ingest a supplied text corpus and create a doc2vec model (the model creation consists of a pre-processing step and the subsequent training of the doc2vec model).
The results of this process are required by the docker framework in the [evidence-gui](https://github.com/ADAH-EviDENce/evidence-gui) repository, and must be loaded and indexed when starting this framework.
Currently the  created model and accompanying output are stored in a docker volume, while the evidence-gui framework expects them to be located at a certain path on the host system.

It would be desirable to either:
- make this interface smoother by atuning the storage solution of the Evidence framework to the Gui
- unify both frameworks

**Comment by jspaaks** [comment]
can this be closed now that the two repos have been merged and are using the same files?

**Comment by jspaaks** [comment]
I'm clsing this because Faruk told me to do it.
