### ISSUE TITLE
Draw a diagram to show how everything is connected.

### ISSUE THREAD

**Issue by fdiblen** [ADAH-EviDENce/evidence#23]

**Comment by meiertgrootes** [comment]
@fdiblen Is this something you guys want to do, or would you like me to provide this?

**Comment by jspaaks** [comment]
If you take a first stab at this, we can start iterating from there

**Comment by meiertgrootes** [comment]
Ok, will do

**Comment by meiertgrootes** [comment]
pull request #67 adds schematic diagram depicting how the original setup worked. Issue can be closed when pull request merged

**Comment by jspaaks** [comment]
was merged, closing
