### ISSUE TITLE
Execute Jupyter notebooks from the command line

### ISSUE THREAD

**Issue by fdiblen** [ADAH-EviDENce/evidence#27]
See:
https://nbconvert.readthedocs.io/en/latest/execute_api.html

**Comment by fdiblen** [comment]
[This action](https://github.com/marketplace/actions/run-notebook) or something similar can be used to test existing Jupyter notebooks. 

Another option:
https://github.com/ReviewNB/treon

**Comment by meiertgrootes** [comment]
Not sure if this is pertinent, but many be worth mentioning:

The notebooks make use of the [`import-ipynb`](https://pypi.org/project/import-ipynb/) package to import the contents of other notebooks. We used this to avoid clutter in the main notebooks, and place utility functions with their documentation in other notebooks, which were then imported.
This does, however, require the notebooks to be imported to reside in the same directory from which the notebook importing them is being executed.

This may or may not impact methods for automatic execution, but I thought it to be worth mentioning

**Comment by fdiblen** [comment]
implemented in #61
