### ISSUE TITLE
Fix linting issues

### ISSUE THREAD

**Issue by fdiblen** [ADAH-EviDENce/evidence#30]
https://github.com/ADAH-EviDENce/WorkingTitleCloseReader/runs/849988353?check_suite_focus=true
spend 30 minutes at most on this

**Comment by fdiblen** [comment]
@meiertgrootes It would be nice if you could try to fix linting issues of framework

**Comment by jspaaks** [comment]
More up to date link is https://github.com/ADAH-EviDENce/WorkingTitleCloseReader/actions?query=workflow%3A%22Lint+Code+Base%22

**Comment by fdiblen** [comment]
Created a PR on evidence-gui repo and asked maintainers to fix linting the issues.
See:
https://github.com/knaw-huc/evidence-gui/pull/5

**Comment by fdiblen** [comment]
@meiertgrootes ui is excluded in linting now. Could you work on fixing framework related linting issues?

**Comment by meiertgrootes** [comment]
yes, I will.

**Comment by meiertgrootes** [comment]
made pull request #87 which fixes linting errors based off of `remove-framework` branch. Request review by @fdiblen. Can be closed on merge.

**Comment by meiertgrootes** [comment]
PR #87 merged. closing
