### ISSUE TITLE
framework's run_evidence_framework.sh generates a bunch of files,

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#33]
would be better to generate them under a pre-existing directory, maybe ``/generated`` or ``/build`` or something, see for example here https://github.com/research-software-directory/research-software-directory/tree/master/docker-volumes

**Comment by jspaaks** [comment]
Or, ``output`` in #50

**Comment by fdiblen** [comment]
Fixed in #61 
The generated files are saved to:
- ``${PWD}/experiments/${EXPERIMENT}`` folder in host
- ``/data`` folder in the running container
