### ISSUE TITLE
representation API needs POST instead of GET

### ISSUE THREAD

**Issue by sverhoeven** [ADAH-EviDENce/evidence#34]
Trying to open http://127.0.0.1:5001/corpusmodelrep results in 405 `Method not allowed` error. I was able to access it with POST method using `curl -X post http://127.0.0.1:5001/corpusmodelrep`. The requests should be made with a GET instead of a POST.

**Comment by meiertgrootes** [comment]
You're right, of course. I think this is a copy past error in the instructions, for the vector representation and inference POST must be used to supply the required argument for the API, but the corpus representation doesn't need that and should be configured for GET

**Comment by jspaaks** [comment]
Is this fixed enough with the updated README?

**Comment by fdiblen** [comment]
It is documented and the web server is not being used anymore.
