### ISSUE TITLE
Elasticsearch warns about low free disk

### ISSUE THREAD

**Issue by sverhoeven** [ADAH-EviDENce/evidence#36]
I get the following warning bringing up the gui 

```
elasticsearch_1  | [2020-07-08T14:38:16,394][INFO ][o.e.c.r.a.DiskThresholdMonitor] [HH7wVdU] low disk watermark [85%] exceeded on [HH7wVdUvRkmwK2x6L3MwlA][HH7wVdU][/usr/share/elasticsearch/data/nodes/0] free: 53.6gb[12.1%], replicas will not be assigned to this node
```

I was able to solve it by adding `cluster.routing.allocation.disk.threshold_enabled: 'false'` to the `docker-compose.yml:services:elasticsearch:environment` map.

**Comment by cwmeijer** [comment]
add this flag as default

**Comment by sverhoeven** [comment]
Let's no hide warnings, but let user act on it
