### ISSUE TITLE
gui compose has hardcoded paths for indexer

### ISSUE THREAD

**Issue by sverhoeven** [ADAH-EviDENce/evidence#37]
The `docker-compose.yml` of the gui has "data/Getuigen_Verhalen_ids" and "data/Getuigen_Verhalen_corpus" hardcoded in the indexer command. This causes `FileNotFoundError: [Errno 2] No such file or directory: 'data/Getuigen_Verhalen_ids'` error and a empty index. After renaming my files the indexer has something in it.

Fetched from elasticsearch container by getting it's ip and running ` curl http://172.22.0.3:9200/snippets/_search | jq .`

**Comment by cwmeijer** [comment]
will be dealt with while fixing #45

**Comment by jspaaks** [comment]
Is this fixed enough by the updated README instructions?

**Comment by sverhoeven** [comment]
Updated README is a placeholder and will be replaced by much more simpler/explicit instructions. For example from the current README it is not clear what I should change those 2 lines into.

For me I needed to set it to

```
"data/Getuigen_Verhalen_ids",
 "data/Getuigen_Verhalen_corpus",
```

**Comment by fdiblen** [comment]
we will use environment variables in docker-compose files.

**Comment by sverhoeven** [comment]
Fixes by selecting an experiment the paths can stay hardcoded.
