### ISSUE TITLE
Gui does not understand corpus model representation

### ISSUE THREAD

**Issue by sverhoeven** [ADAH-EviDENce/evidence#38]
I downloaded `doc2vec.json` with `curl -X post http://127.0.0.1:5001/corpusmodelrep |jq . > doc2vec.json`, I then copied it to `<gui repo>/data/doc2vec.json`.

The server gives the following error

```
server_1         | Starting server
server_1         | 2020/07/08 14:43:50 json: cannot unmarshal array into Go value of type map[string][]float32
evidence-gui_server_1 exited with code 1
```

**Comment by sverhoeven** [comment]
Removing the surrounding array fixed it and I am able to search documents in the gui.

```json
[
  true,
  <keep this>
]
```

**Comment by meiertgrootes** [comment]
Thanks for finding this. In addition to being able to query the corpus representation via the API in thus fashion, the during the construction of the model the notebook generatinig the doc2vec model also saves the model representation in a json file in the /output/model/ folder (as mentioned in #35 )

**Comment by sverhoeven** [comment]
Thanks, the file  `output/model/*.corpus_vectors.js` is already in the right format. So that can be used for automation,

**Comment by meiertgrootes** [comment]
Great, although I guess it would then be good to nevertheless change the representation returned by the API to make it a valid json response.

**Comment by cwmeijer** [comment]
#45

**Comment by jspaaks** [comment]
Is this solved by having the updated README?

**Comment by fdiblen** [comment]
Yes, @jspaaks.
