### ISSUE TITLE
specify docker-compose required version

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#40]
I had to update 

 https://github.com/ADAH-EviDENce/WorkingTitleCloseReader/blob/2b652230b150639e73fff3f44a0e72aab7703088/framework/docker-compose.yml#L71-L76

to

```docker-compose
      - volume_data:/home/jovyan/input/:ro,nocopy
```

which may be due to my docker-compose being version 1.14

**Comment by sverhoeven** [comment]
I was using docker-compose version 1.25.4, and did not need to change file

**Comment by fdiblen** [comment]
also docker version?

**Comment by sverhoeven** [comment]
I am using Docker version 19.03.12

**Comment by jspaaks** [comment]
done, closing
