### ISSUE TITLE
develop user experience / customer journey

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#41]
I'd like us to write down how we think a person will find this tool, then be convinced that it can help them solve a problem they're having, then the steps that they will take to get to a result that is useful to them.

**Comment by sverhoeven** [comment]
Proposed possible journey:

As a researcher
1. First I would like to get familiar with possibilities of the tool. I would like to bring up the user interface with an demonstration dataset with the minimal amount of steps.
2. When the user interface has been explored and I am sure I can use it then I would like to use my own corpus. I will convert my corpus to the format the tool wants.  Then I want to train a built-in model on my corpus and bring up the user interface. At this moment I don't care if the results are the best they can be, I just want to see my corpus in the user interface. The training can take a while so I would like some feedback about the progress.
3. ~~If have explored my corpus in the tool, but the finding of related documents/fragments is not so good. I have an idea how I could improve the model. To implement my improvements I would like to supply my own model training script/notebook. After supplying my corpus and model training script I would like to train the model and bring up the user interface.~~ out of scope for milestone
4. I have a model that I am happy with. Now I would like to bring up the user interface without having to wait for the model to train again. The assisted closed reading can now be done with my own corpus and my own optimized model.

**Comment by fdiblen** [comment]
As developers we should:

Step 1.
   In the README
  - Introduce the tool
  - Explain what it can do for researchers and what are the limitations (corpus size etc.)
  - Show a demo which does not require complicated steps like model training
    - Use predefined corpus and model for the demo
    - Show a screencast
    - Show screenshots
    - Show online demo (if we can find a free tier with docker-compose support: what about KNAW server?)
  - Show simple instructions to bring up the demo: 
    - install ``docker`` and ``docker-compose``
    - clone the repo
    - run ``docker-compose --build up --env-file experiements/demo/config.env``

Step 2.
  - Describe what are the requirements for the corpus format and show an example (predefined corpus and model)
  - Instructions on training
    - create a folder for your experiment under experiments/YOUR_EXPERIMENT
    - add your corpus to experiments/YOUR_EXPERIMENT/corpus
    - describe config.env file
    - the default experiment is demo and the folder is ``experiments/getuigenverhalen``
    - run ``docker-compose --env-file config.env run model-generation``
    - the progress should be visible to the user
  - Show the corpus and model using ui
    - run ``docker-compose --build up --env-file experiments/getuigenverhalen/config.env``

~~Step 3.~~
  ~~- Add steps for generating a new model.~~
 ~~- Add instructions for creating and using own model.~~

Step 4.
  - Add instructions to use existing model.
    - the model must in experiments/YOUR_EXPERIMENT/ folder
    - run ``docker-compose --build up --env-file experiments/YOUR_EXPERIMENT/config.env``
