### ISSUE TITLE
inform user of training progress or whether it has completed

### ISSUE THREAD

**Issue by cwmeijer** [ADAH-EviDENce/evidence#44]
what file was created or such
For instance, wrap reinfer_corpus_single() with ProgressBar.
For training the model with GenSim it would be nice to have a progressbar for the epochs it has done as this is a fixed number.

**Comment by jspaaks** [comment]
Could be relevant:

https://github.com/iomega/spec2vec/blob/5437ca8c56289a3e93d8859596f17d2d59d139b1/spec2vec/model_building.py#L87-L94

**Comment by fdiblen** [comment]
Added in #95
