### ISSUE TITLE
Create a demo experiment

### ISSUE THREAD

**Issue by fdiblen** [ADAH-EviDENce/evidence#55]
- [x] move ``input`` folder to ``experiments/demo/corpus``
- [x] generate the model 
- [x] create a config.env file

**Comment by sverhoeven** [comment]
Attached what I needed in `evidedence-gui/data/` to run the ui based on the example corpus.
[demo-model.tar.gz](https://github.com/ADAH-EviDENce/WorkingTitleCloseReader/files/4913181/demo-model.tar.gz)

**Comment by sverhoeven** [comment]
@jspaaks added/moved experiments/getuigenverhalen, but this contains only 2 projects of getuigenverhalen (see #28 for links) 

Is this the set we want to use for the demo? Or do we want more projects or some thing else completely?

**Comment by fdiblen** [comment]
- We used ``experiments/getuigenverhalen/corpus`` instead of ``experiments/demo/corpus``
- The model is generated in Docker container using:
```shell
jupyter nbconvert --to notebook --execute generate_doc2vec_model.ipynb --ExecutePreprocessor.timeout=3600 && rm generate_doc2vec_model.nbconvert.ipynb || exit 1
```
- Instead of using ``config.env``, we used a single environment variable which must be set before building the images.
For example:
``EXPERIMENT=getuigenverhalen``
