### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by sverhoeven** [ADAH-EviDENce/evidence#6]
Do we need to support users with the Windows operating system?

Docker is supported on Windows and the shell script could be run in WSL, but this might be to cumbersome.

**Comment by meiertgrootes** [comment]
It seems likely that the majority of the target users (humanities scholars with vested interest in traditional methods like close reading) will likely be running windows. 
One of the original ideas behind using docker was also that it would be easier to use on windows. So if possible, some kind of (at least instructions) for windows would be good, I believe

**Comment by sverhoeven** [comment]
Started working on instructions to get the demo running on Windows.

**Comment by cwmeijer** [comment]
PR #68 contains the instructions and fixes this issue.

**Comment by sverhoeven** [comment]
Chapter for running demo on Windows has been merged.
