### ISSUE TITLE
why smart_open instead of built-in open?

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#62]

**Comment by sverhoeven** [comment]
It supports files/urls from cloud storage.. Now we have the capability to open files from AWS S3 for example, but we are not using it.

**Comment by sverhoeven** [comment]
@meiertgrootes agrees smart_open is not needed.

**Comment by jspaaks** [comment]
I removed it as a dependency during #61, removed ``import``s from the notebooks, and changed ``smart_open`` to ``open`` in the notebooks, but somehow that results in ``smart_open`` related errors, which may come from importing ``gensim`` (which uses ``smart_open`` as one of its dependencies). ``pip install``ing ``smart-open`` fixed it, so I added that to the ``environment.yml`` in #61.
