### ISSUE TITLE
Ask upstream if the license can be changed to Apache-2.0

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#7]
Otherwise the combined tool also needs to become GPL-3.0, and we need to "document changes"...not sure what that entails legally.

https://github.com/knaw-huc/evidence-gui

**Comment by meiertgrootes** [comment]
Although I followed up on the license issue (after searching for dependencies requiring this license in their code and not finding any) a release was made under the original GPL3+ license. @jspaaks I guess this sets the license situation in stone? After the stand-up yesterday my understanding is that we will work with the orig. GPL3+ license.
