### ISSUE TITLE
remove pickling?

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#71]
Is the pickle file being used anywhere? If not, we could remove it. This would

- remove dependency ``pandas``
- simplify configuration

**Comment by meiertgrootes** [comment]
this can be removed. The same output is available in the json file. The pkl file is legacy output, and only useful if the model and reinferrred vectors are to be exported and reloaded into a (different) gensim instance.

**Comment by meiertgrootes** [comment]
answer was deemed sufficient
