### ISSUE TITLE
Unable to access frontend remotely

### ISSUE THREAD

**Issue by sverhoeven** [ADAH-EviDENce/evidence#77]
When I have the frontend running and try to access it by the machines ip adres there is an error fetching the users. The error message is `Er trad een fout op bij het ophalen van de gebruikers.`.

**Comment by jspaaks** [comment]
I assume this is after you did the curl XPOST user?

**Comment by sverhoeven** [comment]
Yes, i did.

For example when visiting http://192.168.1.3:8080 from my machine with ip 192.168.1.2 the react app fetches users from http://localhost:8080/users, which fails

**Comment by sverhoeven** [comment]
Oops, the elastic search query done by the web service server can not find the es server.

**Comment by sverhoeven** [comment]
Seems JS elastic search client defaults to localhost when host is set to '/'.

**Comment by sverhoeven** [comment]
Now whole frontend works remotely
