### ISSUE TITLE
Add to RSD

### ISSUE THREAD

**Issue by fdiblen** [ADAH-EviDENce/evidence#8]

**Comment by fdiblen** [comment]
better to resolve #13 first

**Comment by jspaaks** [comment]
working on it here https://www.research-software.nl/admin/software/evidence and https://www.research-software.nl/software/evidence.

**Comment by jspaaks** [comment]
Unpublished the RSD entry again, awaiting input from @meiertgrootes on #94 , and making a release (#9)

**Comment by jspaaks** [comment]
Published the page; this issue is now superseded by #116
