### ISSUE TITLE
Add to Zenodo

### ISSUE THREAD

**Issue by fdiblen** [ADAH-EviDENce/evidence#9]
- [x] Grant Zenodo app permissions for this org
- [x] Flip the switch on "WorkingTitleCloseReader" here https://zenodo.org/account/settings/github/ @meiertgrootes 
- [x] Add citation metadata, i.e. a ``CITATION.cff`` 
- [x] Convert CFF to ``.zenodo.json`` ~~(blocked by #13)~~
- [x] Make a release #11

**Comment by meiertgrootes** [comment]
switch flipped

**Comment by jspaaks** [comment]
some documentation https://github.com/NLeSC/guide/blob/master/citable_software/making_software_citable.md

**Comment by fdiblen** [comment]
better to resolve #13 first

**Comment by meiertgrootes** [comment]
@jspaaks @cwmeijer @sverhoeven @fdiblen Please add your orcid (if you wish) to the CITATION.cff file in the [CFF_zenodo_files](https://github.com/ADAH-EviDENce/evidence/tree/CFF_zenodo_files) branch.

**Comment by jspaaks** [comment]
FYI @cwmeijer @fdiblen I added your orcids already

**Comment by meiertgrootes** [comment]
ready as far as I'm concerned. can be closed if #91 is accepted and merged

**Comment by jspaaks** [comment]
> can be closed if #91 is accepted and merged

and we have created a release
