### ISSUE TITLE
Explain how evidence can help a user solve their problem

### ISSUE THREAD

**Issue by jspaaks** [ADAH-EviDENce/evidence#94]
Add section to the top of the README

**Comment by jspaaks** [comment]
Should this be part of the milestone? I think so.

**Comment by jspaaks** [comment]
@meiertgrootes what is the status of this issue?

**Comment by meiertgrootes** [comment]
Working in it. Got delayed by the work on the bug fix. Hope to complete by end of the day

**Comment by meiertgrootes** [comment]
Initial explanation now present. @jspaaks Sufficient to close this issue?
